version: "3.9"

networks:
    web:
      driver:  bridge

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g

  crawler:
    build: .
    depends_on:
      - chrome
    command:
      - sh
      - -c
      - |
        ./wait-for-it.sh chrome:4444 -t 10
        python -m musinsa_crawler
    networks:
      - web
    volumes:
      - ./output:/crawler/output
    env_file:
      - crawler.env